import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Nav from "./Components/Nav";
import Footer from "./Components/Footer";
import { Person } from "./page";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const myName: Person = {
  first: "Alexis",
  last: "Dogins",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Nav person={myName} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
